name: Packt eBook downloader

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create the config file on the fly
        run: |
          ls -lah 
          cp config/prod_example.cfg config/prod.cfg
          
          echo "Change the configuration files"
          sed -i 's/PACKTPUB_EMAIL/myemail@gmail.com/' config/prod.cfg
          sed -i 's/PACKTPUB_PASSWORD/mypassword/' config/prod.cfg
          cat config/prod.cfg
      
      - name: Download the ebooks
        uses: isabryant/packtcli-docker/downloader@main
        with:
          src_folder: /github/workspace/_drafts/
          dest_folder: /github/workspace/_drafts/
          days_mask: Tue
          dry_run: false
          nb_days_ahead: 7
          
